URL_SERVICE = "https://dbe2d3d0-809b-46d6-94a9-824c12d8acdc.serverhub.praktikum-services.ru"
DOC_PATH = "/docs/"
CREATE_USER_PATH = "/api/v1/users/"
LOG_MAIN_PATH = "/api/logs/main/"
USERS_TABLE_PATH = "/api/db/resources/user_model.csv"
PRODUCTS_KITS_PATH = "/api/v1/products/kits/"